import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import jsPDF from 'jspdf';
import './ResultsPanel.css';

function ScoreMeter({ score }) {
  const color = score >= 70 ? '#10b981' : score >= 40 ? '#f59e0b' : '#ef4444';
  const label = score >= 70 ? 'Likely Authentic' : score >= 40 ? 'Uncertain' : 'Likely False';
  const circumference = 2 * Math.PI * 54;
  const dashOffset = circumference - (score / 100) * circumference;

  return (
    <div className="score-meter">
      <svg width="140" height="140" viewBox="0 0 140 140">
        <circle cx="70" cy="70" r="54" fill="none" stroke="#1e2d4a" strokeWidth="12" />
        <motion.circle
          cx="70" cy="70" r="54"
          fill="none"
          stroke={color}
          strokeWidth="12"
          strokeLinecap="round"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset: dashOffset }}
          transition={{ duration: 1.2, ease: 'easeOut' }}
          transform="rotate(-90 70 70)"
        />
        <motion.text
          x="70" y="65"
          textAnchor="middle"
          fill={color}
          fontSize="26"
          fontWeight="800"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
        >
          {score}
        </motion.text>
        <text x="70" y="82" textAnchor="middle" fill="#94a3b8" fontSize="11">/ 100</text>
      </svg>
      <motion.p
        className="score-label"
        style={{ color }}
        initial={{ opacity: 0, y: 5 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.8 }}
      >
        {label}
      </motion.p>
    </div>
  );
}

function FindingRow({ finding, index }) {
  const statusColor = { good: '#10b981', bad: '#ef4444', warn: '#f59e0b', info: '#3b82f6' };
  const statusIcon = { good: '✓', bad: '✗', warn: '⚠', info: 'ℹ' };
  return (
    <motion.div
      className="finding-row"
      initial={{ opacity: 0, x: -15 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: index * 0.06 }}
    >
      <span className="finding-status" style={{ color: statusColor[finding.status] || '#94a3b8' }}>
        {statusIcon[finding.status] || '•'}
      </span>
      <span className="finding-label">{finding.label}</span>
      <span className="finding-value" style={{ color: statusColor[finding.status] || 'var(--text-secondary)' }}>
        {finding.value}
      </span>
    </motion.div>
  );
}

function ExifSection({ exifData }) {
  const [expanded, setExpanded] = useState(false);
  const entries = Object.entries(exifData || {}).filter(([k, v]) => v != null && typeof v !== 'object');

  if (!entries.length) return null;
  const shown = expanded ? entries : entries.slice(0, 8);

  return (
    <div className="exif-section">
      <h3 className="section-subtitle">EXIF Metadata ({entries.length} fields)</h3>
      <div className="exif-grid">
        {shown.map(([k, v]) => (
          <div key={k} className="exif-row">
            <span className="exif-key">{k}</span>
            <span className="exif-value">{String(v).slice(0, 80)}</span>
          </div>
        ))}
      </div>
      {entries.length > 8 && (
        <button className="btn-expand" onClick={() => setExpanded(!expanded)}>
          {expanded ? '▲ Show less' : `▼ Show ${entries.length - 8} more fields`}
        </button>
      )}
    </div>
  );
}

export default function ResultsPanel({ results, inputData, apiKey }) {
  const panelRef = useRef(null);

  const downloadPDF = () => {
    const doc = new jsPDF();
    const lines = [];
    lines.push('HowSus - Authenticity Analysis Report');
    lines.push('');
    lines.push(`Date: ${new Date().toLocaleString()}`);
    lines.push(`Type: ${results.type.toUpperCase()}`);
    lines.push(`Input: ${inputData.value?.slice(0, 80) || inputData.file?.name || 'N/A'}`);
    lines.push('');
    lines.push(`Authenticity Score: ${results.score}/100`);
    lines.push(`Verdict: ${results.score >= 70 ? 'Likely Authentic' : results.score >= 40 ? 'Uncertain' : 'Likely False'}`);
    lines.push('');
    lines.push('FINDINGS:');
    (results.findings || []).forEach(f => {
      lines.push(`  [${f.status?.toUpperCase()}] ${f.label}: ${f.value}`);
    });
    if (results.duplicates?.length) {
      lines.push('');
      lines.push('SIMILAR SOURCES:');
      results.duplicates.forEach(d => lines.push(`  ${d.source} - ${d.similarity}% similarity (${d.date})`));
    }
    if (results.aiAnalysis) {
      lines.push('');
      lines.push('AI ANALYSIS:');
      const aiLines = results.aiAnalysis.match(/.{1,90}/g) || [];
      aiLines.forEach(l => lines.push('  ' + l));
    }
    lines.push('');
    lines.push('Generated by HowSus - News & Media Authenticity Analyzer');

    let y = 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(lines[0], 15, y); y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    lines.slice(1).forEach(line => {
      if (y > 270) { doc.addPage(); y = 15; }
      doc.text(line, 15, y); y += 7;
    });
    doc.save(`howsus-report-${Date.now()}.pdf`);
  };

  const downloadHTML = () => {
    const score = results.score;
    const color = score >= 70 ? '#10b981' : score >= 40 ? '#f59e0b' : '#ef4444';
    const verdict = score >= 70 ? 'Likely Authentic' : score >= 40 ? 'Uncertain' : 'Likely False';

    const findingsHTML = (results.findings || []).map(f => {
      const sc = { good: '#10b981', bad: '#ef4444', warn: '#f59e0b', info: '#3b82f6' };
      return `<tr><td style="color:${sc[f.status]}">${f.label}</td><td style="color:${sc[f.status]}">${f.value}</td></tr>`;
    }).join('');

    const dupHTML = results.duplicates?.length ? `
      <h3>Similar Sources (${results.duplicates.length})</h3>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%;border-color:#334155">
        <tr><th>Source</th><th>Similarity</th><th>Date</th></tr>
        ${results.duplicates.map(d => `<tr><td>${d.source}</td><td>${d.similarity}%</td><td>${d.date}</td></tr>`).join('')}
      </table>` : '';

    const aiHTML = results.aiAnalysis ? `<h3>AI Analysis</h3><p style="background:#1e293b;padding:12px;border-radius:8px;line-height:1.6">${results.aiAnalysis}</p>` : '';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HowSus Report - ${new Date().toLocaleDateString()}</title>
<style>
  body { font-family: Arial, sans-serif; background: #0a0e1a; color: #f1f5f9; padding: 32px; max-width: 900px; margin: 0 auto; }
  h1 { color: #3b82f6; } h2 { color: #8b5cf6; margin-top: 28px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { padding: 8px 12px; border: 1px solid #1e2d4a; text-align: left; }
  th { background: #111827; }
  .score { font-size: 4rem; font-weight: 900; color: ${color}; }
  .verdict { font-size: 1.2rem; color: ${color}; margin-bottom: 20px; }
  .footer { margin-top: 40px; color: #475569; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>🔍 HowSus - Authenticity Report</h1>
<p>Generated: ${new Date().toLocaleString()}</p>
<p>Type: ${results.type.toUpperCase()} | Input: ${(inputData.value || inputData.file?.name || 'N/A').slice(0, 100)}</p>
<div class="score">${score}</div>
<div class="verdict">${verdict}</div>
<h2>Analysis Findings</h2>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;border-color:#334155">
  <tr><th>Check</th><th>Result</th></tr>
  ${findingsHTML}
</table>
${dupHTML}
${aiHTML}
<div class="footer">Generated by HowSus - News & Media Authenticity Analyzer</div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `howsus-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <motion.section
      className="results-panel"
      ref={panelRef}
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.5 }}
    >
      <div className="results-card">
        <div className="results-header">
          <h2>Analysis Results</h2>
          <div className="download-btns">
            <button className="btn-download pdf" onClick={downloadPDF} title="Download PDF report">
              ⬇ PDF
            </button>
            <button className="btn-download html" onClick={downloadHTML} title="Download HTML report">
              ⬇ HTML
            </button>
          </div>
        </div>

        <div className="results-top">
          <ScoreMeter score={results.score} />
          <div className="results-summary">
            <div className="summary-item">
              <span className="summary-key">Input type</span>
              <span className="summary-val">{results.type.toUpperCase()}</span>
            </div>
            {results.domain && (
              <div className="summary-item">
                <span className="summary-key">Domain</span>
                <span className="summary-val">{results.domain}</span>
              </div>
            )}
            {results.wordCount && (
              <div className="summary-item">
                <span className="summary-key">Words</span>
                <span className="summary-val">{results.wordCount}</span>
              </div>
            )}
            {results.fileName && (
              <div className="summary-item">
                <span className="summary-key">File</span>
                <span className="summary-val">{results.fileName}</span>
              </div>
            )}
            {results.exifCount !== undefined && (
              <div className="summary-item">
                <span className="summary-key">EXIF fields</span>
                <span className="summary-val">{results.exifCount}</span>
              </div>
            )}
            {results.duplicates?.length > 0 && (
              <div className="summary-item">
                <span className="summary-key">Similar sources</span>
                <span className="summary-val warn">{results.duplicates.length} found</span>
              </div>
            )}
          </div>
        </div>

        <div className="section-divider" />

        <div className="findings-section">
          <h3 className="section-subtitle">Detailed Findings</h3>
          {results.findings?.map((f, i) => <FindingRow key={i} finding={f} index={i} />)}
        </div>

        {results.type === 'image' && results.exifData && Object.keys(results.exifData).length > 0 && (
          <>
            <div className="section-divider" />
            <ExifSection exifData={results.exifData} />
          </>
        )}

        {results.duplicates?.length > 0 && (
          <>
            <div className="section-divider" />
            <div className="duplicates-section">
              <h3 className="section-subtitle">Source Duplication ({results.duplicates.length} matches)</h3>
              <div className="dup-list">
                {results.duplicates.map((d, i) => (
                  <motion.div
                    key={i}
                    className="dup-item"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: i * 0.07 }}
                  >
                    <span className="dup-source">{d.source}</span>
                    <div className="dup-bar-wrap">
                      <motion.div
                        className="dup-bar"
                        style={{ background: d.similarity > 80 ? '#ef4444' : d.similarity > 65 ? '#f59e0b' : '#10b981' }}
                        initial={{ width: 0 }}
                        animate={{ width: `${d.similarity}%` }}
                        transition={{ duration: 0.8, delay: i * 0.07 }}
                      />
                    </div>
                    <span className="dup-pct">{d.similarity}%</span>
                    <span className="dup-date">{d.date}</span>
                  </motion.div>
                ))}
              </div>
            </div>
          </>
        )}

        {results.aiAnalysis && (
          <>
            <div className="section-divider" />
            <div className="ai-section">
              <h3 className="section-subtitle">🤖 AI Analysis</h3>
              <motion.div
                className="ai-content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
              >
                {results.aiAnalysis}
              </motion.div>
            </div>
          </>
        )}

        {results.error && (
          <div className="error-msg">⚠ {results.error}</div>
        )}
      </div>
    </motion.section>
  );
}
